# services:

#   db:
#     image: postgres:18
#     restart: always
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
#       interval: 10s
#       retries: 5
#       start_period: 30s
#       timeout: 10s
#     volumes:
#       - app-db-data:/var/lib/postgresql/data/pgdata
#     env_file:
#       - .env
#     environment:
#       - PGDATA=/var/lib/postgresql/data/pgdata
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
#       - POSTGRES_USER=${POSTGRES_USER?Variable not set}
#       - POSTGRES_DB=${POSTGRES_DB?Variable not set}

#   adminer:
#     image: adminer
#     restart: always
#     networks:
#       - traefik-public
#       - default
#     depends_on:
#       - db
#     environment:
#       - ADMINER_DESIGN=pepa-linha-dark
#     labels:
#       - traefik.enable=true
#       - traefik.docker.network=traefik-public
#       - traefik.constraint-label=traefik-public
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.rule=Host(`adminer.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.entrypoints=http
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.middlewares=https-redirect
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.rule=Host(`adminer.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.entrypoints=https
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.tls=true
#       - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-https.tls.certresolver=le
#       - traefik.http.services.${STACK_NAME?Variable not set}-adminer.loadbalancer.server.port=8080

#   prestart:
#     image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
#     build:
#       context: ./backend
#     networks:
#       - traefik-public
#       - default
#     depends_on:
#       db:
#         condition: service_healthy
#         restart: true
#     command: bash scripts/prestart.sh
#     env_file:
#       - .env
#     environment:
#       - DOMAIN=${DOMAIN}
#       - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
#       - ENVIRONMENT=${ENVIRONMENT}
#       - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
#       - SECRET_KEY=${SECRET_KEY?Variable not set}
#       - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
#       - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
#       - SMTP_HOST=${SMTP_HOST}
#       - SMTP_USER=${SMTP_USER}
#       - SMTP_PASSWORD=${SMTP_PASSWORD}
#       - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
#       - POSTGRES_SERVER=db
#       - POSTGRES_PORT=${POSTGRES_PORT}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER?Variable not set}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
#       - SENTRY_DSN=${SENTRY_DSN}

#   backend:
#     image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
#     restart: always
#     networks:
#       - traefik-public
#       - default
#     depends_on:
#       db:
#         condition: service_healthy
#         restart: true
#       prestart:
#         condition: service_completed_successfully
#     env_file:
#       - .env
#     environment:
#       - DOMAIN=${DOMAIN}
#       - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
#       - ENVIRONMENT=${ENVIRONMENT}
#       - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
#       - SECRET_KEY=${SECRET_KEY?Variable not set}
#       - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
#       - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
#       - SMTP_HOST=${SMTP_HOST}
#       - SMTP_USER=${SMTP_USER}
#       - SMTP_PASSWORD=${SMTP_PASSWORD}
#       - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
#       - POSTGRES_SERVER=db
#       - POSTGRES_PORT=${POSTGRES_PORT}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_USER=${POSTGRES_USER?Variable not set}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
#       - SENTRY_DSN=${SENTRY_DSN}

#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#     build:
#       context: ./backend
#     labels:
#       - traefik.enable=true
#       - traefik.docker.network=traefik-public
#       - traefik.constraint-label=traefik-public

#       - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=8000

#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=Host(`api.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.entrypoints=http

#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.rule=Host(`api.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.entrypoints=https
#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls=true
#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-https.tls.certresolver=le

#       # Enable redirection for HTTP and HTTPS
#       - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.middlewares=https-redirect

#   frontend:
#     image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
#     restart: always
#     networks:
#       - traefik-public
#       - default
#     build:
#       context: ./frontend
#       args:
#         - VITE_API_URL=https://api.${DOMAIN?Variable not set}
#         - NODE_ENV=production
#     labels:
#       - traefik.enable=true
#       - traefik.docker.network=traefik-public
#       - traefik.constraint-label=traefik-public

#       - traefik.http.services.${STACK_NAME?Variable not set}-frontend.loadbalancer.server.port=80

#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.rule=Host(`dashboard.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.entrypoints=http

#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.rule=Host(`dashboard.${DOMAIN?Variable not set}`)
#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.entrypoints=https
#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.tls=true
#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-https.tls.certresolver=le

#       # Enable redirection for HTTP and HTTPS
#       - traefik.http.routers.${STACK_NAME?Variable not set}-frontend-http.middlewares=https-redirect

#   grafana:
#     image: grafana/grafana:latest
#     restart: always
#     ports:
#       - "3000:3000"
#     volumes:
#       - grafana-data:/var/lib/grafana

    
# volumes:
#   app-db-data:
#   grafana-data:

# networks:
#   traefik-public:
#     # Allow setting it to false for testing
#     external: true

services:

  db:
    image: postgres:18
    restart: always
    env_file:
      - .env.prod
    volumes:
      - app-db-data:/var/lib/postgresql/data

  prestart:
    image: bfdiego/fullstack-backend:latest
    depends_on:
      - db
    env_file:
      - .env.prod
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: bash scripts/prestart.sh

  backend:
    image: bfdiego/fullstack-backend:latest
    restart: always
    depends_on:
      - db
      - prestart
    env_file:
      - .env.prod
    ports:
      - "8000:8000"

  frontend:
    image: bfdiego/fullstack-frontend:latest
    ports:
      - "80:80"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:2.9.3
    volumes:
      - ./observability/loki/loki-config.yml:/etc/loki/config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./observability/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/etc/grafana/dashboards

volumes:
  app-db-data:
  grafana-data:
  prometheus-data:
  loki-data: